#cloud-config
# Cloud config for application servers 

runcmd:
  - init_role=jenkinsmaster
  - init_env=dev
  - init_repouser=mitese
  - init_reponame=server-provisioning
  - init_repobranch=master
  - init_configbucket=https://s3-us-ease-1.amazonaws.com/config.intview1

  - exec 1>/var/log/boot.log 2>&1
  - set -x

  - yum -y update
  - yum -y install git

  - cd /opt/
  - git clone https://github.com/neilmillard/mitese-boot.git
  - chmod a+x /opt/provision.sh
  - ./provision.sh --role ${init_role} --environment ${init_env} --repouser ${init_repouser} --reponame ${init_reponame} --repobranch ${init_repobranch}